export enum RoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  STATE_ADMIN = 'STATE_ADMIN',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  STAFF = 'STAFF',
  PARENT = 'PARENT',
  STUDENT = 'STUDENT'
}